version = 0.1

[default]
stack_name = "japanese-learn"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default.deploy.parameters]
stack_name = "japanese-learn"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []